# Generated by Django 5.2.8 on 2025-11-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_clientes_produtos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagemcontato',
            old_name='mensagem',
            new_name='descricao',
        ),
    ]
