# Generated by Django 5.2.8 on 2025-11-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_rename_mensagem_mensagemcontato_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemcontato',
            name='celular',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
    ]
