# Generated by Django 4.2.25 on 2025-11-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_mensagemcontato_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
