# Generated by Django 5.2.8 on 2025-11-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_clientes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='valor',
        ),
    ]
